#!/bin/bash
DIR=$1
wget http://www.cptec.inpe.br/cidades/tempo/228# -O $DIR/clima -q
killall wget
CLIMA1=`cat $DIR/clima`
CLIMA=""
#rm $DIR/clima
GRAVAR=false
for i in $CLIMA1
  do
	case $i in
		*id=\"sub3\"\>*)
			GRAVAR=true
			;;
		*\"c7\"\>*)
			GRAVAR=false
			;;
	esac
	if [[ $GRAVAR = true ]];then
		CLIMA=$CLIMA$i
	fi
  done
GRAVAR=false
OPCAO=""

	for i in `seq 0 ${#CLIMA}`
		 do
			if [[ ${CLIMA:$i:8} = \/icones\/ ]];then
				x=$i
				while [[ ${CLIMA:$x:1} != \" ]];do
					x=$(($x+1))
					y=$(($y+1))
				done
				DIA=${CLIMA:$(($i+8)):$(($y-8))}
			fi
			case "${CLIMA:$i:3}" in
			  \<b\>)GRAVAR=true;;
			  \<\/b)GRAVAR=false;;
			  \<im)if [[ $OPCAO = c5 ]];then
					GRAVAR=false;OPCAO=v5;fi;;
			  c2*)OPCAO=c2;;
			  c3*)OPCAO=c3;;
			  c4*)OPCAO="";;
			  c5*)OPCAO=c5;;
			esac
			if [[ $GRAVAR = true ]];then
				case $OPCAO in
				c2)TEMP=$TEMP${CLIMA:$i:1};;
				c3)UMID=$UMID${CLIMA:$i:1};;
				c5)DIRV=$DIRV${CLIMA:$i:1};;
				v5)VELV=$VELV${CLIMA:$i:6};OPCAO="";;
				esac
			fi
			if [[ $OPCAO = v5 && ${CLIMA:$i:1} = \> ]];then
				GRAVAR=true
			fi
	done
TEMP=${TEMP:3}
echo "Temperatura: "$TEMP" ºC"
UMID=${UMID:3}
echo "Umidade: "$UMID
DIRV=${DIRV:3}
echo "Direção do vento: "$DIRV
echo "Velocidade do vento: "$VELV
var=`ls -l $DIR/clima`
echo "Ultima atualização: "${var:38:5}
if [[ $TEMP = "" && $UMID = "" ]];then
	echo n > $DIR/dados/baixou
else
	echo y > $DIR/dados/baixou
fi
if [[ `cat $DIR/dados/foto` != $DIR/icones/$DIA ]];then
	sed -i "s|`cat $DIR/dados/foto`|$DIR/icones/$DIA|g" $HOME/.conkyrc
	echo $DIR/icones/$DIA > $DIR/dados/foto
fi

