/* Generated by re2c 2.0.3 on Tue May 18 05:06:17 2021 */
#line 1 "re2c_teste.re"
#include <stdio.h>

static int lex(const char *YYCURSOR)
{
    const char *YYMARKER;
    
#line 10 "re2c_teste.c"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '0':	goto yy4;
	default:	goto yy2;
	}
yy2:
	++YYCURSOR;
yy3:
#line 13 "re2c_teste.re"
	{ printf("err\n"); return 1; }
#line 23 "re2c_teste.c"
yy4:
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'x':	goto yy5;
	default:	goto yy3;
	}
yy5:
	yych = *++YYCURSOR;
	if (yych >= 0x01) goto yy8;
yy6:
	YYCURSOR = YYMARKER;
	goto yy3;
yy7:
	yych = *++YYCURSOR;
yy8:
	switch (yych) {
	case 0x00:	goto yy9;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy7;
	default:	goto yy6;
	}
yy9:
	++YYCURSOR;
#line 14 "re2c_teste.re"
	{ printf("hex\n"); return 0; }
#line 69 "re2c_teste.c"
}
#line 15 "re2c_teste.re"

}

int main(int argc, char **argv)
{
    for (int i = 1; i < argc; ++i) {
        lex(argv[i]);
    }
    return 0;
}
