#!/bin/bash
KEY=artur
PORT=10022
for i in $@;do
	case $i in
		--port=*)
			PORT="${i:7}";;
		--key=*)KEY="${i:6}";;
	esac
done
export GIT_SSH_COMMAND="ssh -i $HOME/.ssh/${KEY} -p ${PORT}"
echo Command: $GIT_SSH_COMMAND
