#!/bin/bash

my_dir="$(dirname "$0")"

#. "$my_dir/catchline"
OUTPUT=""
FIRST=true
AS_R=false
DIR=$1
#for i in $@
#	do
					
#	done

for i in `find $1`
	do
		if [[ -n `cat $i 2>/dev/null |grep $2 ` ]]
			then
				if [[ $FIRST == true ]]
					then
						FIRST=false
					else
						OUTPUT+=$'\n'
				fi
				OUTPUT+=$i
		fi
	done;
if [[ -n $3 ]]
	then
		echo "$OUTPUT" | $my_dir/catchline $3
	else
		echo "$OUTPUT"
fi
