#!/bin/bash
#################################################
# author: Artur Bernardo Mallmann
# email: arturbmallmann (at) gmail (dot) com
#################################################

debug=false
# for imports:
# my_dir="$(dirname "$0")" 
#. "$my_dir/catchline" or source "" to load functions and attributes

OUTPUT=""
KEYWORD=""
GPARAM=""
help () {
	echo "Use:"
	echo "	grepfiles dir word [catchoutputline] [grep options]"
	echo "Arguments:"
	echo "	-r/-R for recursive search"
}

function sif () {
	FIRST=true
		for i in $@
			do
				if [[ -n `cat $i 2>/dev/null |grep $GPARAM $KEYWORD ` ]]
					then
						if [[ $FIRST == true ]]
							then
								FIRST=false
							else
								OUTPUT+=$'\n'
						fi
						OUTPUT+=$i
				fi
			done;
			return 0
}

function catchline () {
	head -n $1 |tail -n 1
}

function main () {

	argc=0
	REC=false
	line=0
	for arg in $@
		do
		case $arg in
			-R)
				REC=true
				;;
			-r)
				REC=true
				;;
			--help)
				help
				exit
				;;
			-*)
				echo [entrou]
				GPARAM+=$arg
				;;
			*)
				case $argc in
					0) 
						FOLDER=$arg
						;;
					1) 
						KEYWORD=$arg
						;;
					2)
						line=$arg
				esac
				argc=$((argc + 1))
				;;
		esac
	done
	if $REC
		then
		FILES=`find $FOLDER`
	else
		FILES=`ls ${FOLDER}`
	fi

	if [[ -n $KEYWORD ]]
		then
		sif $FILES
	else
		help
	fi

	if [[ $line -ne 0 ]]
		then
			echo "$OUTPUT" | catchline $line
#			echo "$OUTPUT" |$my_dir/catchline $line
		else
			echo "$OUTPUT"
	fi
}

main $@

