#!/bin/sh
LOG=/var/log/trim.log
echo "*** $(date -R) ***" >> $LOG
fstrim -v / >> $LOG
fstrim -v /home >> $LOG 
#/etc/cron.daily/trim
#fonte: http://www.edivaldobrito.com.br/como-ativar-o-trim-em-discos-ssd-no-ubuntu-linux/
#fonte: http://ubuntuhandbook.org/index.php/2013/12/enable-trim-ssd-better-performance/
